/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Dic.Data;
import Dic.MySQL;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author votun
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin1
     */
    private String tu, pa, lt, ng, am, anh;
    private int id;

    public Admin() {
        initComponents();
        showDataInTable();
        setLocationRelativeTo(this);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (JOptionPane.showConfirmDialog(null,
                        "Are you sure to close this window?", "Really Closing?",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                    dispose();
//                    Index in = new Index();
//                    in.setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTu = new javax.swing.JLabel();
        jTFTu = new javax.swing.JTextField();
        jLPAm = new javax.swing.JLabel();
        jTFPAm = new javax.swing.JTextField();
        jLLoaiTu = new javax.swing.JLabel();
        jTFLoaiTu = new javax.swing.JTextField();
        jLNghia = new javax.swing.JLabel();
        jTFNghia = new javax.swing.JTextField();
        jLAm = new javax.swing.JLabel();
        jTFAm = new javax.swing.JTextField();
        jLAnh = new javax.swing.JLabel();
        jTFAnh = new javax.swing.JTextField();
        jLBId = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jBUpdate = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jBInsert = new javax.swing.JButton();
        jLTitle = new javax.swing.JLabel();
        jBReload = new javax.swing.JToggleButton();
        jBReload1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBOImage = new javax.swing.JButton();
        jBOAudio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLTu.setText("Từ");

        jLPAm.setText("Phiên Âm");

        jLLoaiTu.setText("Loại Từ");

        jLNghia.setText("Nghĩa");

        jTFNghia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNghiaActionPerformed(evt);
            }
        });

        jLAm.setText("Âm Thanh");

        jLAnh.setText("Ảnh");

        jLBId.setText("Id");

        jBUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Update_40px_1.png"))); // NOI18N
        jBUpdate.setText("Update");
        jBUpdate.setPreferredSize(new java.awt.Dimension(65, 23));
        jBUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpdateActionPerformed(evt);
            }
        });

        jBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Delete_20px.png"))); // NOI18N
        jBDelete.setText("Delete");
        jBDelete.setPreferredSize(new java.awt.Dimension(65, 23));
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jBInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Insert_40px_1.png"))); // NOI18N
        jBInsert.setText("Insert");
        jBInsert.setPreferredSize(new java.awt.Dimension(65, 23));
        jBInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertActionPerformed(evt);
            }
        });

        jLTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLTitle.setForeground(new java.awt.Color(255, 0, 0));
        jLTitle.setText("DICTIONARY APP DEMO");

        jBReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Refresh_15px_2.png"))); // NOI18N
        jBReload.setText("Reload");
        jBReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReloadActionPerformed(evt);
            }
        });

        jBReload1.setText("Clear");
        jBReload1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReload1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Từ", "PhiênÂm", "LoạiTừ", "Nghĩa", "Âm", "Ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(7);
        }

        jBOImage.setText("...");
        jBOImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOImageActionPerformed(evt);
            }
        });

        jBOAudio.setText("...");
        jBOAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOAudioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLAnh)
                        .addGap(58, 58, 58)
                        .addComponent(jTFAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPAm)
                            .addComponent(jLTu)
                            .addComponent(jLBId))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFTu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFPAm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBReload1))))
                    .addComponent(jLLoaiTu, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jTFLoaiTu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLNghia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFNghia, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLAm)
                        .addGap(29, 29, 29)
                        .addComponent(jTFAm, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jBInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jBUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBOImage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBOAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBReload)
                        .addGap(175, 175, 175))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTitle)
                .addGap(261, 261, 261))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBDelete, jBInsert, jBUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jBReload)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLBId)
                            .addComponent(jBReload1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLTu)
                            .addComponent(jTFTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPAm)
                            .addComponent(jTFPAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLLoaiTu)
                            .addComponent(jTFLoaiTu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNghia)
                            .addComponent(jTFNghia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLAm)
                                    .addComponent(jTFAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLAnh)
                                        .addComponent(jTFAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBOImage, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jBOAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBDelete, jBInsert, jBUpdate});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpdateActionPerformed

        if ("".equals(jTFTu.getText())) {

            JOptionPane.showMessageDialog(null, "Import Data Please !!!!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {

            update();
        }
        clearTable();
        showDataInTable();
    }//GEN-LAST:event_jBUpdateActionPerformed

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        if ("".equals(jTFTu.getText())) {

            JOptionPane.showMessageDialog(null, "Import Data Please !!!!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {

            delete();
            clear();

        }
        clearTable();
        showDataInTable();
    }//GEN-LAST:event_jBDeleteActionPerformed

    private void jBInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertActionPerformed
        if ("".equals(jTFTu.getText())) {

            JOptionPane.showMessageDialog(null, "Import Data Please !!!!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {

            insert();

        }
        clearTable();
        showDataInTable();
    }//GEN-LAST:event_jBInsertActionPerformed
    public void insert() {
        tu = jTFTu.getText();
        pa = jTFPAm.getText();
        lt = jTFLoaiTu.getText();
        ng = jTFNghia.getText();
        am = jTFAm.getText();
        anh = jTFAnh.getText();
        MySQL.adInsert(tu, pa, lt, ng, am, anh);

    }

    public void delete() {
        tu = jTFTu.getText();
        MySQL.adDelete(tu);
    }

    public void update() {
        tu = jTFTu.getText();
        pa = jTFPAm.getText();
        lt = jTFLoaiTu.getText();
        ng = jTFNghia.getText();
        am = jTFAm.getText();
        anh = jTFAnh.getText();
        id = Integer.parseInt(jTFId.getText());
        MySQL.adUpdate(tu, pa, lt, ng, am, anh, id);

    }

    public void clearTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);

    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        jTFId.setText(model.getValueAt(i, 0).toString());
        jTFTu.setText(model.getValueAt(i, 1).toString());
        jTFPAm.setText(model.getValueAt(i, 2).toString());
        jTFLoaiTu.setText(model.getValueAt(i, 3).toString());
        jTFNghia.setText(model.getValueAt(i, 4).toString());
        jTFAm.setText(model.getValueAt(i, 5).toString());
        jTFAnh.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReloadActionPerformed
        clearTable();
        showDataInTable();
    }//GEN-LAST:event_jBReloadActionPerformed

    private void jBReload1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReload1ActionPerformed
       clear();
    }//GEN-LAST:event_jBReload1ActionPerformed

    private void jTFNghiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNghiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNghiaActionPerformed

    private void jBOAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOAudioActionPerformed
        JFileChooser c = new JFileChooser();
        FileNameExtensionFilter ef = new FileNameExtensionFilter("Audio Files", "mp3");
        c.setFileFilter(ef);
        int a = c.showOpenDialog(null);
        if (a == JFileChooser.APPROVE_OPTION) {
            File file = c.getSelectedFile();
            file.renameTo(new File("C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\Audio\\" + jTFTu.getText() + "." + getExtension(file)));
            String path = file.getAbsolutePath();
            String path1 = "C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\Audio\\" + jTFTu.getText() + "." + getExtension(file);
            jTFAm.setText(path1);
        }

    }//GEN-LAST:event_jBOAudioActionPerformed
    public String getExtension(File f) {
        if (!f.getName().contains("")) {
            return "";
        } else {
            return f.getName().substring(f.getName().length() - 3, f.getName().length());
        }
    }
    private void jBOImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOImageActionPerformed
        JFileChooser c = new JFileChooser();
        FileNameExtensionFilter ef = new FileNameExtensionFilter("Image Files", "png", "jpg");
        c.setFileFilter(ef);
        int a = c.showOpenDialog(null);
        if (a == JFileChooser.APPROVE_OPTION) {
            File file = c.getSelectedFile();
            file.renameTo(new File("C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\Image1\\" + jTFTu.getText() + "." + getExtension(file)));
            String path = file.getAbsolutePath();
            String path1 = "C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\Image1\\" + jTFTu.getText() + "." + getExtension(file);
            jTFAnh.setText(path1);
        }
    }//GEN-LAST:event_jBOImageActionPerformed

    public void showDataInTable() {

        ArrayList<Data> list = MySQL.getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getTu();
            row[2] = list.get(i).getpAm();
            row[3] = list.get(i).getlTu();
            row[4] = list.get(i).getNg();
            row[5] = list.get(i).getAm();
            row[6] = list.get(i).getAnh();

            model.addRow(row);
        }
    }
    public void clear(){
        jTFTu.setText("");
        jTFPAm.setText("");
        jTFLoaiTu.setText("");
        jTFNghia.setText("");
        jTFAm.setText("");
        jTFAnh.setText("");
        jTFId.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(DicGui.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBInsert;
    private javax.swing.JButton jBOAudio;
    private javax.swing.JButton jBOImage;
    private javax.swing.JToggleButton jBReload;
    private javax.swing.JToggleButton jBReload1;
    private javax.swing.JButton jBUpdate;
    private javax.swing.JLabel jLAm;
    private javax.swing.JLabel jLAnh;
    private javax.swing.JLabel jLBId;
    private javax.swing.JLabel jLLoaiTu;
    private javax.swing.JLabel jLNghia;
    private javax.swing.JLabel jLPAm;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JLabel jLTu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAm;
    private javax.swing.JTextField jTFAnh;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFLoaiTu;
    private javax.swing.JTextField jTFNghia;
    private javax.swing.JTextField jTFPAm;
    private javax.swing.JTextField jTFTu;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
