/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import Dic.Data;
import Dic.IOF;
import Dic.MySQL;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author votun
 */
public class DicGui extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private String value;

    private String bb;

    private Data nc;

    private static int status = 0;

    private static int code;

    public DicGui() {
        initComponents();
        jLAudio.setVisible(false);
        jLLikee.setVisible(false);
        jScrollPane3.setBorder(null);
        this.setLocationRelativeTo(null);
        MySQL.dsTu(jList1);
        this.jTFSearch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                DefaultListModel list = (DefaultListModel) jList1.getModel();
                list.removeAllElements();
                String b = jTFSearch.getText();
                MySQL.search(b, jList1);
                jLBImage.setIcon(null);
                jEditorPane1.setText("");
               // System.out.println(b + jList1);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String b = jTFSearch.getText();
                MySQL.search(b, jList1);
                jLBImage.setIcon(null);
                jEditorPane1.setText("");
                jLAudio.setVisible(false);
                jLLikee.setVisible(false);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                System.out.println("change");
            }
        });
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (JOptionPane.showConfirmDialog(null,
                        "Are you sure to close this window?", "Really Closing?",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                    dispose();

                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLSearch = new javax.swing.JLabel();
        jLHistory = new javax.swing.JLabel();
        jLLike = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTFSearch = new javax.swing.JTextField();
        jBSearch = new javax.swing.JButton();
        jBClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLAudio = new javax.swing.JLabel();
        jLBImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLLikee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 69, 127));
        jPanel2.setPreferredSize(new java.awt.Dimension(498, 67));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Open_Book_50px_1.png"))); // NOI18N
        jLabel4.setText(" Definition");
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, 533, 66));

        jPanel5.setBackground(new java.awt.Color(244, 244, 244));

        jPanel6.setBackground(new java.awt.Color(5, 53, 102));

        jLSearch.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLSearch.setForeground(new java.awt.Color(140, 179, 210));
        jLSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Search_30px_1.png"))); // NOI18N
        jLSearch.setToolTipText("Search\n");
        jLSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSearchMouseClicked(evt);
            }
        });

        jLHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Clock_30px.png"))); // NOI18N
        jLHistory.setToolTipText("History");
        jLHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLHistoryMouseClicked(evt);
            }
        });

        jLLike.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Star_30px.png"))); // NOI18N
        jLLike.setToolTipText("Like");
        jLLike.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLikeMouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dictionary App Demo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLSearch)
                .addGap(32, 32, 32)
                .addComponent(jLHistory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLLike)
                .addGap(32, 32, 32))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSearch)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLLike)
                        .addComponent(jLHistory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jTFSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFSearch.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTFSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTFSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFSearchMouseClicked(evt);
            }
        });
        jTFSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFSearchKeyPressed(evt);
            }
        });

        jBSearch.setBackground(new java.awt.Color(255, 255, 255));
        jBSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Binoculars_20px_2.png"))); // NOI18N
        jBSearch.setToolTipText("Search");
        jBSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBSearchMouseClicked(evt);
            }
        });

        jBClear.setBackground(new java.awt.Color(255, 255, 255));
        jBClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Delete_20px.png"))); // NOI18N
        jBClear.setToolTipText("Clear");
        jBClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTFSearch)
                .addGap(0, 0, 0)
                .addComponent(jBClear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jBSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jBSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Audio_25px_1.png"))); // NOI18N
        jLAudio.setToolTipText("Audio");
        jLAudio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLAudioMouseClicked(evt);
            }
        });

        jEditorPane1.setEditable(false);
        jEditorPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(jEditorPane1);

        jLLikee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Star_25px_4.png"))); // NOI18N
        jLLikee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLikeeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAudio)
                    .addComponent(jLLikee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLBImage, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLLikee))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBImage, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 66, 534, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSearchMouseClicked
        jLSearch.setEnabled(true);
        jLHistory.setEnabled(false);
        jLLike.setEnabled(false);
        jList1.setVisible(true);
        MySQL.dsTu(jList1);
        jTFSearch.setEnabled(true);
        jBSearch.setEnabled(true);
        jBClear.setEnabled(true);
    }//GEN-LAST:event_jLSearchMouseClicked

    private void jLHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLHistoryMouseClicked
        jLHistory.setEnabled(true);
        jLSearch.setEnabled(false);
        jLLike.setEnabled(false);
        DefaultListModel list = (DefaultListModel) jList1.getModel();
        list.removeAllElements();
        jTFSearch.setEnabled(false);
        jBSearch.setEnabled(false);
        MySQL.showHistory(code, jList1);

    }//GEN-LAST:event_jLHistoryMouseClicked

    private void jLLikeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLikeMouseClicked
        jLLike.setEnabled(true);
        jLSearch.setEnabled(false);
        jLHistory.setEnabled(false);
        DefaultListModel list = (DefaultListModel) jList1.getModel();
        list.removeAllElements();
        jTFSearch.setEnabled(false);
        jBSearch.setEnabled(false);
        MySQL.showLike(code, jList1);


    }//GEN-LAST:event_jLLikeMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        jLAudio.setVisible(true);
        jLLikee.setVisible(true);
        value = jList1.getSelectedValue();
        jTFSearch.setText(value);
        setEP();
        addImage();


    }//GEN-LAST:event_jList1MouseClicked

    private void jTFSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            value = jTFSearch.getText();
            setEP();
            addImage();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jList1.requestFocusInWindow();
            jList1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jTFSearchKeyPressed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            value = jList1.getSelectedValue();
            setEP();
            addImage();
        }

    }//GEN-LAST:event_jList1KeyPressed

    private void jTFSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFSearchMouseClicked

        //jList1.setSelectedIndex(-1);

    }//GEN-LAST:event_jTFSearchMouseClicked

    private void jBSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSearchMouseClicked

        JButton jbutton = (JButton) evt.getSource();
        if (jbutton.isEnabled()) {
            value = jTFSearch.getText();
            setEP();
            addImage();
            if (value.equals("")) {
                JOptionPane.showMessageDialog(null, "Import Data , Please !!!!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBSearchMouseClicked

    private void jLAudioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLAudioMouseClicked

        MySQL.audio(nc.getAm());
    }//GEN-LAST:event_jLAudioMouseClicked

    private void jBClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClearMouseClicked

        jTFSearch.setText("");
        jEditorPane1.setText("");
        jLBImage.setIcon(null);
        jLAudio.setVisible(false);
        jLLikee.setVisible(false);

        if (jLHistory.isEnabled() && jLSearch.isEnabled() == false && jLLike.isEnabled() == false) {
            MySQL.showHistory(code, jList1);
        }
        if (jLLike.isEnabled() && jLHistory.isEnabled() == false && jLSearch.isEnabled() == false) {
            MySQL.showLike(code, jList1);
        }

    }//GEN-LAST:event_jBClearMouseClicked

    private void jLLikeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLikeeMouseClicked

        ImageIcon image1 = new ImageIcon("C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\image\\icons8_Star_25px_3.png");
        ImageIcon image2 = new ImageIcon("C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\image\\icons8_Star_25px_4.png");
        if (status == 0) {
            status = 1;
            jLLikee.setIcon(image1);
            MySQL.like(nc.getTu(), code);
        } else {
            status = 0;
            jLLikee.setIcon(image2);
            MySQL.unLike(nc.getTu(), code);
        }

    }//GEN-LAST:event_jLLikeeMouseClicked
    public void addImage() {
        ImageIcon image = new ImageIcon(nc.getAnh());
        jLBImage.setIcon(image);

    }

    public void setEP() {
        String pa, tu, ltu, ng, tran;
        nc = MySQL.transTu(value);
        if (nc.getTu() == null) {
            JOptionPane.showMessageDialog(null, "Can't Find Data !!!!", "ERRO", JOptionPane.ERROR_MESSAGE);
            jLAudio.setVisible(false);
            jLLikee.setVisible(false);
        } else {
            jLAudio.setVisible(true);
            jLLikee.setVisible(true);
            jEditorPane1.setContentType("text/html");
            tu = "<b><font size=+3 color=black>" + nc.getTu() + "</font></b>";

            pa = "<font size=+2 color=red>" + nc.getpAm() + "</font>";

            ltu = "<font size=+2 >" + nc.getlTu() + "</font>";

            ng = "<font size=+2 >" + nc.getNg() + "</font>";

            tran = "&#9" + tu + "&#9" + pa + "<br>" + "&#9" + ltu + "<br>" + "&#9" + ng;
            jEditorPane1.setText(tran);

        }
        MySQL.history(nc.getTu(), code);
        status = MySQL.statusLike(nc.getTu(), code);
        ImageIcon image1 = new ImageIcon("C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\image\\icons8_Star_25px_4.png");
        ImageIcon image2 = new ImageIcon("C:\\Users\\votun\\Documents\\NetBeansProjects\\JavaApplication1\\src\\image\\icons8_Star_25px_3.png");
        if (status == 0) {

            jLLikee.setIcon(image1);

        } else {

            jLLikee.setIcon(image2);

        }

    }

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException, IOException {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(DicGui.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            //new Index().setVisible(true);
            new DicGui().setVisible(true);
        }
        );
        if (IOF.oF() == null) {
            code = 1;
            IOF.iF(String.valueOf(code));
        } else {
            code = Integer.parseInt(IOF.oF());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClear;
    private javax.swing.JButton jBSearch;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLAudio;
    private javax.swing.JLabel jLBImage;
    private javax.swing.JLabel jLHistory;
    private javax.swing.JLabel jLLike;
    private javax.swing.JLabel jLLikee;
    private javax.swing.JLabel jLSearch;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFSearch;
    // End of variables declaration//GEN-END:variables
}
